apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordle-operator

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wordles.operators.lucasmelin.com
spec:
  group: operators.lucasmelin.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                guess:
                  type: string
                  description: The word to guess
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: wordles
    singular: wordle
    kind: Wordle
    shortNames:
      - wd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle-operator
  labels:
    app: wordle-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordle-operator
  template:
    metadata:
      labels:
        app: wordle-operator
    spec:
      serviceAccountName: wordle-operator
      containers:
        - name: wordle-operator
          image: ghcr.io/lucasmelin/wordle-operator:latest
          imagePullPolicy: Always

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wordle-operator
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create, patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["operators.lucasmelin.com"]
    resources: ["wordle"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wordle-operator
subjects:
  - kind: ServiceAccount
    name: wordle-operator
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: wordle-operator
  apiGroup: rbac.authorization.k8s.io
